### ISSUE TITLE
QUESTION: How add Catalyst option to the GitHub Action

### ISSUE THREAD

**Issue by fermoya** [unsignedapps/swift-create-xcframework#25]
I've noticed that [version 1.3.0](https://github.com/unsignedapps/swift-create-xcframework/releases/tag/v1.3.0) started supporting Catalyst compilation if `--platform maccatalyst` is passed as an argument in the terminal.

How can I do the same in a GitHub Action? Apologies, I haven't been able to find any documentation about supported environment variables to pass to the action.

**Comment by fermoya** [comment]
I'm gonna answer myself on this one:
```yml
    steps:
      - uses: actions/checkout@v2

      - name: Create XCFramework
        uses: unsigned/swift-create-xcframework@v1.3
        with:
          platforms: ios, macos, maccatalyst, tvos, watchos
```
