### ISSUE TITLE
[BUG] GitHub Action always uses version 1.0.5 which fails to compile with new SPM

### ISSUE THREAD

**Issue by fermoya** [unsignedapps/swift-create-xcframework#26]
First of all, thanks for the tool and the effort to support it.

I'm having an issue using the GitHub Action. I noticed it was using an old version `v1.0.5` and I decided to update it in my GitHub flow YML. Before, I had:
```
  create_xcframework:
    name: Create XCFramework
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v1
```
I changed it to:
```
  create_xcframework:
    name: Create XCFramework
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v1.3
```
and didn't work. Finally, I tried:
```
  create_xcframework:
    name: Create XCFramework
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v1.3.0
```
In all of them, it seems `mint` tries to use an old version that doesn't work with SPM. This was fixed in newer versions, I believe. The error I get is always the same:
```
/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/mint/github.com_unsignedapps_swift-create-xcframework/.build/checkouts/swift-llbuild/products/llbuildSwift/BuildSystemBindings.swift:687:54: warning: initialization of 'UnsafePointer<UnsafePointer<CChar>?>' (aka 'UnsafePointer<Optional<UnsafePointer<Int8>>>') results in a dangling pointer
105
        _invocation.environment = _cEnvironment.map{ UnsafePointer($0.envp) }
106
                                                     ^~~~~~~~~~~~~~~~~~~~~~
...
...
...
🌱 Encountered error during "swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx10.15". Use --verbose to see full output
133
🌱  Failed to build swift-create-xcframework 1.0.5 with SPM
134
Error: Error: The process '/usr/local/bin/mint' failed with exit code 1
```
So I believe the problem is the GitHub Action is installing the wrong version? See the whole dialog [here](https://github.com/fermoya/SwiftUIPager/runs/1322096291?check_suite_focus=true)

**swift-create-xcframework version:** `1.3.0` but problem is GitHub Action references version 1.0.5
**Swift version:** 5.3
**Environment:** Doesn't apply, it's an image deployed by GitHub

### Checklist
- [✓] If possible, I've reproduced the issue using the `master` branch of this package
- [✓] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

Create a repo, set up a github action and use it:
```
  create_xcframework:
    name: Create XCFramework
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v1.3.0
```

See the whole dialog [here](https://github.com/fermoya/SwiftUIPager/runs/1322096291?check_suite_focus=true)

### Expected behavior

GitHub Action uses latest version.

### Actual behavior

GitHub Action uses old version 1.0.5
