### ISSUE TITLE
Providing  target to github action

### ISSUE THREAD

**Issue by nihartsx** [unsignedapps/swift-create-xcframework#77]
according to the document, "By default swift-create-xcframework will build XCFrameworks for all library products in your Package.swift, or any targets you specify on the command line (this can be for any dependencies you include as well).".

I am using Github action, and i'd like to just build xcframework of two products only.  

```
- name: Create XCFramework
  uses: unsignedapps/swift-create-xcframework@v2.3.0
  with:
      target: "Target1,Target2"
```

This does not seem to work, it picks up a third target that causes xcframework to fail and i would like to leave it out of the job.  

Locally i can pass target, ex.  `swift create-xcframework Target1 Target2 Target3`. but is there a similar solution for github action?

**Comment by nihartsx** [comment]
```
- name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v2.3.0
        with:
          target: "ProductOne,ProductTwo"
```

This does not seem to work, it picks up a third target that causes xcframework to fail and i would like to leave it out of the job.
